# Generated by Django 3.2.6 on 2023-05-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='desc',
            new_name='description',
        ),
    ]
